version: "3.9"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: manisankarrr/portfolio:latest
    ports:
      - "3000:80"        # Map localhost:3000 → container’s port 80
    volumes:
      - ./dist:/usr/share/nginx/html:ro   # Mount host dist/ into Nginx webroot (read-only)
