name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint (if configured)
        run: npm run lint

      - name: Build production bundle
        run: npm run build

      - name: Preview & smoke-test
        run: |
          npm run preview -- --port 5173 &
          sleep 5
          curl --fail http://localhost:5173 || exit 1
